// Generates ODR-DabMux .mux configuration file from MuxConfig
import { MuxConfig } from "./types";

export function generateMuxFile(config: MuxConfig): string {
  const lines: string[] = [];

  lines.push("; ===================================================");
  lines.push("; Generated by Viva Libido DAB+ Mux Server");
  lines.push(`; Generated at: ${new Date().toISOString()}`);
  lines.push("; ===================================================");
  lines.push("");

  // General section
  lines.push("general {");
  lines.push(`    dabmode ${config.general.dabmode}`);
  lines.push(`    nbframes ${config.general.nbframes}`);
  lines.push(`    syslog ${config.general.syslog}`);
  lines.push(`    tist ${config.general.tist}`);
  lines.push(`    managementport ${config.general.managementport}`);
  lines.push("}");
  lines.push("");

  // Remote control section
  lines.push("remotecontrol {");
  if (config.remotecontrol.telnetEnabled) {
    lines.push(`    telnetport ${config.remotecontrol.telnetPort}`);
  }
  if (config.remotecontrol.zmqEnabled) {
    lines.push(`    zmqctrl ${config.remotecontrol.zmqEndpoint}`);
  }
  lines.push("}");
  lines.push("");

  // Ensemble section
  lines.push("ensemble {");
  lines.push(`    id ${config.ensemble.id}`);
  lines.push(`    ecc ${config.ensemble.ecc}`);
  lines.push(`    local-time-offset ${config.ensemble.lto}`);
  lines.push(`    label "${config.ensemble.label}"`);
  lines.push(`    shortlabel "${config.ensemble.shortlabel}"`);
  lines.push("}");
  lines.push("");

  // Services section
  lines.push("services {");
  for (const svc of config.services) {
    lines.push(`    ${svc.id} {`);
    lines.push(`        id ${svc.serviceId}`);
    lines.push(`        label "${svc.label}"`);
    lines.push(`        shortlabel "${svc.shortlabel}"`);
    lines.push(`        pty ${svc.pty}`);
    lines.push(`        language ${svc.language}`);
    lines.push("    }");
  }
  lines.push("}");
  lines.push("");

  // Subchannels section
  lines.push("subchannels {");
  for (const sc of config.subchannels) {
    lines.push(`    ${sc.id} {`);
    lines.push(`        type ${sc.type === "audio" ? "dabplus" : sc.type}`);
    lines.push(`        bitrate ${sc.bitrate}`);
    lines.push(`        protection ${sc.protection}`);

    if (sc.inputType === "zmq") {
      lines.push(`        inputproto zmq`);
      lines.push(`        inputuri "${sc.inputUri}"`);
      if (sc.zmqBufferSize) {
        lines.push(`        zmq-buffer ${sc.zmqBufferSize}`);
      }
      if (sc.zmqPrebuffering) {
        lines.push(`        zmq-prebuffering ${sc.zmqPrebuffering}`);
      }
    } else if (sc.inputType === "edi") {
      lines.push(`        inputproto edi`);
      lines.push(`        inputuri "${sc.inputUri}"`);
    } else if (sc.inputType === "file") {
      lines.push(`        inputproto file`);
      lines.push(`        inputuri "${sc.inputUri}"`);
    } else if (sc.inputType === "sti") {
      lines.push(`        inputproto sti`);
      lines.push(`        inputuri "${sc.inputUri}"`);
    }

    lines.push("    }");
  }
  lines.push("}");
  lines.push("");

  // Components section
  lines.push("components {");
  for (const comp of config.components) {
    lines.push(`    ${comp.id} {`);
    lines.push(`        service ${comp.serviceId}`);
    lines.push(`        subchannel ${comp.subchannelId}`);
    lines.push(`        label "${comp.label}"`);
    if (comp.figType) {
      lines.push(`        figtype ${comp.figType}`);
    }
    if (comp.userApplication) {
      lines.push(`        user-applications {`);
      lines.push(`            ${comp.userApplication} {`);
      lines.push(`            }`);
      lines.push(`        }`);
    }
    lines.push("    }");
  }
  lines.push("}");
  lines.push("");

  // Outputs section
  lines.push("outputs {");
  for (const out of config.outputs) {
    if (!out.enabled) continue;

    if (out.type === "throttle") {
      lines.push(`    ${out.id} "simul://"`);
    } else if (out.type === "simul") {
      lines.push(`    ${out.id} "simul://"`);
    } else if (out.type === "edi-tcp") {
      lines.push(`    ${out.id} {`);
      lines.push(`        protocol tcp`);
      lines.push(`        listenport ${out.port || 13000}`);
      if (out.fec) {
        lines.push(`        fec ${out.fec}`);
      }
      lines.push("    }");
    } else if (out.type === "edi-udp") {
      lines.push(`    ${out.id} {`);
      lines.push(`        protocol udp`);
      lines.push(`        destination "${out.destination || "127.0.0.1"}"`);
      lines.push(`        port ${out.port || 12000}`);
      if (out.sourcePort) {
        lines.push(`        sourceport ${out.sourcePort}`);
      }
      lines.push("    }");
    } else if (out.type === "zmq") {
      lines.push(`    ${out.id} "zmq+tcp://*:${out.port || 18081}"`);
    } else if (out.type === "eti-tcp") {
      lines.push(`    ${out.id} "tcp://localhost:${out.port || 32000}"`);
    } else if (out.type === "file") {
      lines.push(`    ${out.id} "file://${out.destination || "/tmp/dabmux.eti"}"`);
    }
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
